name: JunkJam
title: JunkJam India
description: JunkJam is a global, multi-platform media and entertainment company.
tags:
  - blog
  - template
  - jekyll
  - theme
email: admin@junkjam.in
disqus_username: junkjam
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Team
    url: /team
  - title: Contact
    url: /contact
  - title: Blog
    url: https://blog.junkjam.in
  - title: Drive
    url: https://drive.junkjam.in
  - title: Meme
    url: https://meme.junkjam.in
  - title: WhatsApp
    url: https://whatsapp.junkjam.in
  - title: Feed
    url: /feed.xml
